### PR TITLE
Reusable workflows for plugins to always use latest workflows by default

### PR DESCRIPTION
**Pull request by smvz**
This change should allow clones of this skeleton repository to always use the latest workflows from this repository by default, inspired by the discussion on this meta topic:
https://meta.discourse.org/t/tests-at-github-actions-fail-set-up-redis/208819/6

This could probably do with testing from someone more familiar with plugin development to confirm this behaves as expected.

To summarise the change, the workflows are renamed with their triggers replaced by the `workflow_call` keyword and new workflows are added with a single job to call the reusable workflow in this repository.

### CODE REVIEW

**Comment by QuaqSim** [comment]
Of course they can't be tested as-is.. The `uses` lines will need to be modified to target `QuaqSim/...@reusable-workflows` in order to test this as they currently target files that won't exist before this is merged.

**Comment by smvz** [comment]
The [reusable-workflows-test](https://github.com/QuaqSim/discourse-plugin-skeleton/commits/reusable-workflows-test) branch demonstrates the tests passing with a simple change to target the workflows on this branch. This branch targets currently non-existent workflows on discourse/discourse-plugin-skeleton to simplify merging the pull request.

**Comment by ZogStriP** [comment]
Does this look good @CvX?

**Comment by smvz** [comment]
I have just observed that changes to the linting/tests are usually driven by the workflow in the [discourse/.github](https://github.com/discourse/.github) repository, which must complicate this PR.

Is it specifically desirable for you to be able to update these workflows independently per plugin repository or for another reason, such as triggering the workflow upon merging the discoursebot created PRs? Would it be valuable for me to replace this PR with one on `discourse/.github` instead?

---

If I create the PR there instead, I would essentially make the same change of adding the linting/tests workflows as reusable workflows and update the templates to use a workflow call, as well as make the equivalent change to the theme workflow templates.

After triggering the Update CI workflow and merging the resulting discoursebot PR here (and elsewhere), this repository would have the workflows which simply call the reusable workflows from `discourse/.github`.

**Pull request closed without merging**
