### PR TITLE
DEV: Update CI workflows

### PR DESCRIPTION
**Pull request by discoursebot**
Updates CI from discourse/.github

### CODE REVIEW

**Review by davidtaylorhq — APPROVED** [review]

**Comment by pfaffman** [comment]
I saw that the old tests got broken and I'm watching this repo now, so I pulled in these changes.

But I'm confused -- `tmp` and friends that were deleted from .gitignore should be in some global `.gitignore`?

We don't want to run tests daily to make sure that core hasn't broken the plugin? I recently tried to add this but my nightly tests were failing.

Also, we don't want to run tests when new branches get pushed?

**Comment by davidtaylorhq** [comment]
Sorry @pfaffman, I don't follow. This PR shouldn't have introduced any behaviour change in tests. It was just performance improvements based on https://github.com/discourse/.github/commit/58143a0d9e9d074c8de6fa1a60612cb85aa07e88, and a couple of other housekeeping things

**Comment by pfaffman** [comment]
Weird. I swear that I did a commit that broke and then worked after I pulled in these changes, but it could be my imagination.

But the old CI (before Github actions) would run every day and this seems to run only on a push to main.

I would think that checking all branches on push and doing a daily run would be a good idea and . . . I was hoping that you guys would figure both of these things out and I'd continue to ride on your work. ;-)

**Comment by davidtaylorhq** [comment]
Daily runs are certainly an interesting proposition. For our official plugins, we run their tests alongside every core commit, so running the plugin's own workflows daily is less important. But obviously third-party plugins don't have that luxury.

Adding periodic runs to GitHub actions is fairly doable - we do it in [the discourse_docker repository](https://github.com/discourse/discourse_docker/blob/main/.github/workflows/build.yml#L6-L7), so you could copy/paste that into your plugin. 

Similarly, I think you could make it run on pushes to all branches by removing the `branches: -main` lines, but leave the `push:` line.

**Pull request merged**
